### ISSUE TITLE
Add a Mouse class

### ISSUE THREAD

**Issue by blhough** [SRJC-Computer-Science-Club/micromouse#15]
a class that represents the mouse.
It will at a minimum consist of a position, direction, and functions to move around.

**Comment by joshuasrjc** [comment]
I developed a class, and used the name MouseBot. It consists of position, direction, and functions to move around. I'm planning on adding functions to get input from the sensors, once we have a working "virtual maze."

**Comment by RosyMapleMoth** [comment]
Hay Joshua do you have it in a state where you can put up a pull request I've been working with a sudo mosueBot class to get the core mapping functionality down but it would be nice if I could just switch over to building it around your real mouseBot class.

**Comment by RosyMapleMoth** [comment]
Also MouseBot will need to have two functions that return the direction to the left and right of mouseBot. EDIT if you think this will give you large delays ignore it and I'll make it an issue after MouseBot gets merged.

**Comment by RosyMapleMoth** [comment]
MouseBot has been merged in to dev
