### ISSUE TITLE
Hardware - Function turnTowardsDirection( direction dir )

### ISSUE THREAD

**Issue by Pastyguy** [SRJC-Computer-Science-Club/micromouse#19]
write a function called 'turnTowardsDirection( direction dir )'  assume you know what direction you are facing to begin with

**Comment by joshuasrjc** [comment]
I think I just implemented this function in my branch joshua_mapping. It's called rotateToFaceDirection() and it's part of the MouseBot class. Is this what you meant?

**Comment by blhough** [comment]
yes that should work
