### ISSUE TITLE
resetMap and controller states

### ISSUE THREAD

**Issue by joshuasrjc** [SRJC-Computer-Science-Club/micromouse#61]
- [X] Make sure all mapping data is in the maze class.
- [ ] Implement all states in controller
  - [X] Add a reserMap() function to MouseBot.
  - [ ] change increment speed to use floats
  - [ ] Add exits to any long running function 
  
  *postponed *
- Add save and load functions to Maze that use the Memory class.

**Comment by blhough** [comment]
remind me, did you say that saving a maze would not work?

**Comment by blhough** [comment]
postponing persistent map until there is time
